name: Crypto Imperator
favicon: null
layout_spectrum: 0.4084655772894621
typography_spectrum: 0.04327050130814314
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5795180983841419
  lightness: 0.46316127851605415
  saturation: 0.3019807552918792
  rhythmicContrast: 0.053181424271315336
purpose: []
