name: Crypto Imperator
favicon: null
layout_spectrum: 0.48713
typography_spectrum: 0.67692
title: Crypto Imperator
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8b7f73'
    - '#fffeff'
    - '#110a04'
    - '#c4c1ae'
    - '#fde087'
  brandStrength: 0.125
  lightness: 0.625
  saturation: 0.3019807552918792
  rhythmicContrast: 0.053181424271315336
purpose: []
